SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `ai_bot_test_11` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `ai_bot_test_11`;

CREATE TABLE IF NOT EXISTS `bot_users` (
  `id_bot_users` int NOT NULL AUTO_INCREMENT,
  `tg_id` bigint DEFAULT NULL,
  `tg_username` varchar(33) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `language` varchar(5) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'ru',
  PRIMARY KEY (`id_bot_users`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `user_questions` (
  `id_user_question` int NOT NULL AUTO_INCREMENT,
  `tg_user` int NOT NULL,
  `user_question` varchar(4000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id_user_question`),
  KEY `TG_USER_CONSTRAINT` (`tg_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


ALTER TABLE `user_questions`
  ADD CONSTRAINT `TG_USER_CONSTRAINT` FOREIGN KEY (`tg_user`) REFERENCES `bot_users` (`id_bot_users`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
